using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class ThemeOfTheMonthRandomizer : MonoBehaviour
{

    List<string> themes;
    System.Random rnd;
    int randomNumber;
    string randomTheme;
    public TextMeshProUGUI theme;

    // Start is called before the first frame update
    void Start()
    {
        //Create a List which we will populate
        themes = new List<string>();
        themes.Add("To Travel is to Live");
        themes.Add("It is your attitude, not your aptitude that determines your altitude");
        themes.Add("Turn your Obstacles to Opportunities");
        themes.Add("Retro 90s");
        themes.Add("Make Hay while the sun shines");
        themes.Add("Choices in life");
        themes.Add("Dreams & Ambitions");
        themes.Add("Ways to relax");
        themes.Add("On the other hand");
        themes.Add("The first day . . .");
        themes.Add("Around the world");
        themes.Add("Go green for a better tomorrow");
        themes.Add("Unconditional Living");
        themes.Add("Forgive And Forget");
        themes.Add("Love is bliss");
        themes.Add("Time travel");
        themes.Add("It’s ok to be different");
        themes.Add("Laughter is the best medicine");
        themes.Add("To communicate is to evolve");
        themes.Add("Live life fun size");
        themes.Add("Think before you speak, Read before you think");
        themes.Add("The end is just a new beginning");
        themes.Add("The Magic of Believing");
        themes.Add("The Chatterbox , within!");
        themes.Add("Things to do in a lifetime");
        themes.Add("Through a child’s eyes");
        themes.Add("Changing your habits one step at a time");
        themes.Add("Family and Relatives – Proud of our roots");
        themes.Add("Stay healthy, Stay happy");
        themes.Add("Lessons Learned The Hard Way ");
        themes.Add("Lessons My Children Taught Me");
        themes.Add("Jai Kisan");
        themes.Add("4 ways to become successful");
        themes.Add("Never Give Up");
        themes.Add("Go Green. Go Cycling");
        themes.Add("Valentine’s Day");
        themes.Add("Nobody asked me, but . . .");
        themes.Add("Humanity wins");
        themes.Add("You Can, If You Think, You Can");
        themes.Add("Unforgettable Mentors");
        themes.Add("The Chatterbox Within");
        themes.Add("Back to the future");
        themes.Add("First Things First");
        themes.Add("Together we learn, Together we grow");
        themes.Add("The Magic Of Believing");
        themes.Add("Live in the moment");
        themes.Add("Letting Go");
        themes.Add("Dance Like No One is Watching");
        themes.Add("Planting “seeds”");
        themes.Add("The Best Lesson I Never Learned");
        themes.Add("Fan following");
        themes.Add("Why Me, Why This, Why Now");
        themes.Add("A pleasant surprise");
        themes.Add("Aha moments");
        themes.Add("Your Biggest Lie");
        themes.Add("It’s never too late");
        themes.Add("Boss vs Leader");
        themes.Add("Life Long Learning");
        themes.Add("Monsoon and Memories");
        themes.Add("A time for everything and everything in its time");
        themes.Add("Mother, The god on earth");
        themes.Add("We can, I can");
        themes.Add("Anything is possible");
        themes.Add("Coronation 2016");
        themes.Add("HOPE – Hold On Pain Ends");
        themes.Add("Sacrifice is the virtue of brave");
        themes.Add("Cartoon");
        themes.Add("Serving others");
        themes.Add("Read a new book every month");
        themes.Add("Remember When . . .");
        themes.Add("It takes cool people to help a warm Climate.");
        themes.Add("It’s okay to be different");
        themes.Add("Feel the fear and do it anyways");
        themes.Add("It’s all in the mind, you know!");
        themes.Add("Gog green. Go Natural");
        themes.Add("Colors of Life");
        themes.Add("See It to Believe It");
        themes.Add("The Spirit of being Indian");
        themes.Add("One step at a time");
        themes.Add("You can win");
        themes.Add("Life without limits");
        themes.Add("The power of Now");
        themes.Add("Rich Dad, Poor Dad");
        themes.Add("Chanakya in you");
        themes.Add("Nothing is impossible");
        themes.Add("The first chapter");
        themes.Add("See you at the top");
        themes.Add("Hapy hour is 9 to 5");
        themes.Add("One true thing");
        themes.Add("Go tell it");
        themes.Add("Ctrl + Alt + Del");
        themes.Add("A higher voice");
        themes.Add("Meditation");
        themes.Add("The spark is within you");
        themes.Add("The Aha! moment");
        themes.Add("Drive");
        themes.Add("Who moved my cheese");
        themes.Add("Psychology of selling");
        themes.Add("The power of myth");
        themes.Add("Think and grow rich");
        themes.Add("Win no matter what");
        themes.Add("Mindset");
        themes.Add("Unlimited power");
        themes.Add("Make it happen");
        themes.Add("Awaken the giant within");
        themes.Add("Love your life");
        themes.Add("Power of positive thinking");
        themes.Add("Look into the stillness");
        themes.Add("The magic of thinking big");
        themes.Add("One simple idea can  . . .");
        themes.Add("Stay focused");
        themes.Add("Your only limit is you!");
        themes.Add("Never give up");
        themes.Add("If opportunity doesn’t knock, build a door!");
        themes.Add("Be the BEST version of you");
        themes.Add("Be brave");
        themes.Add("You are amazing");
        themes.Add("#GetLoud for Mental Health Week");
        themes.Add("25 years");
        themes.Add("A Christmas Story");
        themes.Add("A New Direction");
        themes.Add("A penny for your thoughts");
        themes.Add("A pleasant surprise");
        themes.Add("A Tribute to Dad");
        themes.Add("A Tribute to Mom");
        themes.Add("A Whale of a Tale");
        themes.Add("Adventure");
        themes.Add("Aha moments");
        themes.Add("Aim for the Stars");
        themes.Add("Airplanes");
        themes.Add("Amelia Earhart");
        themes.Add("Animals");
        themes.Add("Animated Films");
        themes.Add("April Fools");
        themes.Add("Area Contest");
        themes.Add("Astrology");
        themes.Add("Astronomy");
        themes.Add("Astronomy and Astrology, together");
        themes.Add("Astronomy vs Astrology");
        themes.Add("Aurora Borealis");
        themes.Add("Babies");
        themes.Add("Back in Class");
        themes.Add("Back to school");
        themes.Add("Backwards");
        themes.Add("Backwards meeting");
        themes.Add("Backwoods");
        themes.Add("Bad hair day");
        themes.Add("Balance");
        themes.Add("Bank fees");
        themes.Add("BC Day");
        themes.Add("Being ourselves");
        themes.Add("Believe it or not");
        themes.Add("Birth certificate");
        themes.Add("Birthdays");
        themes.Add("Blend In or Stand Out?");
        themes.Add("Blue");
        themes.Add("Blue Screen of Death");
        themes.Add("Board Games");
        themes.Add("Boo! Betcha I scared you! Ha Ha!");
        themes.Add("Book Lovers Day");
        themes.Add("Boss vs Leader");
        themes.Add("Brown Bag Meeting");
        themes.Add("Building a Better World");
        themes.Add("Bumblee Bees");
        themes.Add("Camping");
        themes.Add("Canada Day");
        themes.Add("Capturing the Moment");
        themes.Add("Car racing");
        themes.Add("Caramel sauce");
        themes.Add("Caterpillars");
        themes.Add("Celebrating our success");
        themes.Add("Celebrities");
        themes.Add("Chinese New Year");
        themes.Add("Chizza");
        themes.Add("Chocolate Cupcake Day");
        themes.Add("Choices");
        themes.Add("Choices in Life");
        themes.Add("Christmas / Hanukkah / Boxing Day");
        themes.Add("Christmas!");
        themes.Add("Clean Out Your Refrigerator Day");
        themes.Add("Club Contest");
        themes.Add("Club Elections");
        themes.Add("Club Officer Training");
        themes.Add("Coffee");
        themes.Add("Collectibles");
        themes.Add("Community");
        themes.Add("Compost");
        themes.Add("Contest Training");
        themes.Add("Conundrum Day");
        themes.Add("Cookie Monster");
        themes.Add("Cool runnings");
        themes.Add("Courier du Bois");
        themes.Add("Creativity");
        themes.Add("Crush a Can Day");
        themes.Add("Cuddly Canines");
        themes.Add("Dance Like No One is Watching");
        themes.Add("Deja Vu all over again");
        themes.Add("Disabilites");
        themes.Add("Diversity");
        themes.Add("DNA");
        themes.Add("Dog Days of Summer");
        themes.Add("Dogs");
        themes.Add("Dogs/Cats");
        themes.Add("Doubles");
        themes.Add("Dr Seuss");
        themes.Add("Dreams & Ambitions");
        themes.Add("Dues");
        themes.Add("Earth Day");
        themes.Add("Easter");
        themes.Add("Easter Weekend");
        themes.Add("Edison vs Tesla");
        themes.Add("Education");
        themes.Add("Elections");
        themes.Add("Electronic Greeting Card Day");
        themes.Add("Energy");
        themes.Add("Equinoxes and Soltices");
        themes.Add("Ethics");
        themes.Add("Fall");
        themes.Add("Fall Harvest");
        themes.Add("Famous Actors/Actresses");
        themes.Add("Fathers Day");
        themes.Add("Favorite Cartoon Characters");
        themes.Add("Favorite Movie Stars");
        themes.Add("Feel the fear and do it anyways");
        themes.Add("Festival festivities");
        themes.Add("Festivity Festival");
        themes.Add("Fine Feathered Friends");
        themes.Add("Fireworks");
        themes.Add("Fitness");
        themes.Add("Five steps to success");
        themes.Add("Flight or Fight");
        themes.Add("Focus on Success");
        themes.Add("Focused on Success");
        themes.Add("Food");
        themes.Add("Forgive & Forget");
        themes.Add("Forward");
        themes.Add("Frankenstein");
        themes.Add("Friends");
        themes.Add("Fruit Salad");
        themes.Add("Go For A Ride Day");
        themes.Add("Goals");
        themes.Add("Grandparents");
        themes.Add("Great Leaders");
        themes.Add("Great Movies");
        themes.Add("Greed");
        themes.Add("Groundhogs & Other Rodents");
        themes.Add("Hale-Bopp");
        themes.Add("Halloween");
        themes.Add("Hats");
        themes.Add("Hawaii");
        themes.Add("Hayek vs Keynes");
        themes.Add("Heart and Stroke");
        themes.Add("Heritage");
        themes.Add("Hit The Slopes");
        themes.Add("Hobbies");
        themes.Add("Hockey");
        themes.Add("Holiday Aftermath");
        themes.Add("Holiday meeting");
        themes.Add("Holidays");
        themes.Add("Home Improvement");
        themes.Add("Homecoming");
        themes.Add("Homemakers");
        themes.Add("Ice Cream");
        themes.Add("Ice Cream Sandwich Day");
        themes.Add("If I Had a Million Dollars");
        themes.Add("In Flanders Fields");
        themes.Add("In My Next Life ....");
        themes.Add("Incredible Kids");
        themes.Add("Influence");
        themes.Add("In-Laws & Outlaws");
        themes.Add("International Children's Day");
        themes.Add("International Day of Awesomeness");
        themes.Add("International Day of Friendship");
        themes.Add("International Day of Peace");
        themes.Add("International Day of the Child");
        themes.Add("International Women's Day");
        themes.Add("Is it winter yet?");
        themes.Add("Isaac Newton");
        themes.Add("It's all about M.E. (Member Experience)");
        themes.Add("It's beginning");
        themes.Add("It's My Party Day");
        themes.Add("It's never too late");
        themes.Add("Judges Training");
        themes.Add("Justice");
        themes.Add("Leadership");
        themes.Add("Lessons Learned the Hard Way");
        themes.Add("Libertarian");
        themes.Add("Lifelong Learning");
        themes.Add("Litigation");
        themes.Add("Luck");
        themes.Add("Makeup training");
        themes.Add("Making Choices");
        themes.Add("March Madness");
        themes.Add("Medicine");
        themes.Add("Metal");
        themes.Add("Mike Holmes");
        themes.Add("Milk Day");
        themes.Add("Mission");
        themes.Add("Moments of Truth");
        themes.Add("Money");
        themes.Add("Moose");
        themes.Add("Mothers Day");
        themes.Add("Motivation");
        themes.Add("Movies");
        themes.Add("Moving experience");
        themes.Add("Moving Experiences");
        themes.Add("Multiculturalism");
        themes.Add("Museums");
        themes.Add("Music");
        themes.Add("My car");
        themes.Add("My Dream Job");
        themes.Add("My Favorite Board Game");
        themes.Add("My Favorite Kind of Quiet");
        themes.Add("My First Car");
        themes.Add("Mystery");
        themes.Add("NAFTA");
        themes.Add("National Day of Mourning");
        themes.Add("National Freedom Day");
        themes.Add("National Police Day");
        themes.Add("National Tartan Day");
        themes.Add("New Beginnings");
        themes.Add("New Years Resolutions");
        themes.Add("Northern Gateway Pipeline");
        themes.Add("Nunavut Day");
        themes.Add("Obama");
        themes.Add("Officer Training");
        themes.Add("Open House");
        themes.Add("Optimism - Learned or Lived");
        themes.Add("Our Ancestors");
        themes.Add("Out of the Blue");
        themes.Add("Past, Present, Future");
        themes.Add("Penguins");
        themes.Add("Perserverance");
        themes.Add("Perseverence");
        themes.Add("Pets");
        themes.Add("Photoshop");
        themes.Add("Pictures");
        themes.Add("Pisces");
        themes.Add("Planning");
        themes.Add("Playground");
        themes.Add("Politics");
        themes.Add("Pom Poms");
        themes.Add("Poppies");
        themes.Add("Positive Thinking Day");
        themes.Add("Poster");
        themes.Add("Poverty");
        themes.Add("POWER!");
        themes.Add("Prescriptions for living");
        themes.Add("Presidents");
        themes.Add("Prevention");
        themes.Add("Prime Ministers");
        themes.Add("Puns");
        themes.Add("Put on Your Own Shoes Day");
        themes.Add("Recklessness");
        themes.Add("Reflecting back");
        themes.Add("Rejoicing");
        themes.Add("Religion");
        themes.Add("Remember when…");
        themes.Add("Remembrance");
        themes.Add("Remembrance Day");
        themes.Add("Retirement");
        themes.Add("Reviewing our Goals");
        themes.Add("Riddles");
        themes.Add("Ride Like the Wind Day");
        themes.Add("Right here, right now");
        themes.Add("Rip Rap and Rebar");
        themes.Add("Risktaking");
        themes.Add("Road trips");
        themes.Add("Royalty");
        themes.Add("Satire");
        themes.Add("Scrabble");
        themes.Add("Seasons");
        themes.Add("Share a Smile Day");
        themes.Add("Simplicity Day");
        themes.Add("Soccer");
        themes.Add("Soccer/football");
        themes.Add("Solidarity");
        themes.Add("Sourest Day");
        themes.Add("Space travel");
        themes.Add("Speaker of The House");
        themes.Add("Speaking well");
        themes.Add("Spiders & Other Scary Insects");
        themes.Add("Spooky Times");
        themes.Add("Spring");
        themes.Add("Spring Cleaning");
        themes.Add("Spring Equinox");
        themes.Add("Spring Into Action");
        themes.Add("St Patricks Day");
        themes.Add("Stephen Hawking");
        themes.Add("Steven Harper");
        themes.Add("Storytelling");
        themes.Add("Success");
        themes.Add("Suit Day / Silence");
        themes.Add("Summer");
        themes.Add("Summer Adventures");
        themes.Add("Summer Solstice");
        themes.Add("Sunshine");
        themes.Add("Super Mario");
        themes.Add("Superman");
        themes.Add("Table topics");
        themes.Add("Teachable Moments");
        themes.Add("Teamwork");
        themes.Add("Technicalities");
        themes.Add("Technology");
        themes.Add("Tell a Joke Day");
        themes.Add("Thanksgiving");
        themes.Add("The answer is always yes");
        themes.Add("The best lesson I ever learned");
        themes.Add("The best lesson I never learned");
        themes.Add("The Day the Music Died");
        themes.Add("The Eiffel Tower & Other Landmarks");
        themes.Add("The first day...");
        themes.Add("The Kentucky Derby");
        themes.Add("The last crunch");
        themes.Add("The Lego Movie");
        themes.Add("The Magic of Believing");
        themes.Add("The Worst Gift I Ever Received");
        themes.Add("Tiger Woods");
        themes.Add("Time");
        themes.Add("Time Travel");
        themes.Add("Toastmaster New Year");
        themes.Add("Tongue Twister Day");
        themes.Add("Toys");
        themes.Add("Traditions");
        themes.Add("Transitions");
        themes.Add("Travel");
        themes.Add("Tried and True");
        themes.Add("Truth or Dare");
        themes.Add("Tupac Shakir");
        themes.Add("Uncle and Aunt Day");
        themes.Add("Unforgettable Furry Companions");
        themes.Add("Unforgettable Mentors");
        themes.Add("Vacations");
        themes.Add("Valentines Day");
        themes.Add("Water");
        themes.Add("Weather");
        themes.Add("Weddings");
        themes.Add("Weekend Getaways");
        themes.Add("Why We Do The Things We Do");
        themes.Add("Winter");
        themes.Add("Winter Fun");
        themes.Add("Winter Wonderland");
        themes.Add("Wood work");
        themes.Add("World Mosquito Day");
        themes.Add("World Teachers' Day");
        themes.Add("World's Indigenous People");
        themes.Add("Worth Repeating");
        themes.Add("Wrestling");
        themes.Add("Year End");
        themes.Add("Yellow Bug");
        themes.Add("Yoda");
        themes.Add("You can if you think you can");

    }

    // Update is called once per frame
    void Update()
    {
        
    }

    // Generates random position in list, and prints out the contents
    public void RandomTheme()
    {
        rnd = new System.Random();
        randomNumber = rnd.Next(themes.Count);
        randomTheme = themes[randomNumber];

        theme.text = randomTheme;

    }
}
